### PR TITLE
refactor: add types definition

### PR DESCRIPTION
**Pull request by MohammadHH**
Implemented a small declaration file to provide better types information for users of this library

### CODE REVIEW

**Comment by baekgol** [comment]
I'm so happy that you participated in this library. Thank you for sharing your capacity!
I knew this library need to enhance for convenience and efficiency.
but I don't have much time, so management was neglected.
Thank you again for your contribution.
I hope you will participate more often in the future.

**Comment by baekgol** [comment]
@MohammadHH I don't have used typescript before. But I understood what it features.
Can you please specify an example and usage for index.d.ts to the top of the License in README.md without modifying the existing content?
If you do that, I think other people will be able to use this library more conveniently.

**Comment by MohammadHH** [comment]
> I'm so happy that you participated in this library. Thank you for sharing your capacity! I knew this library need to enhance for convenience and efficiency. but I don't have much time, so management was neglected. Thank you again for your contribution. I hope you will participate more often in the future.

Thanks, I built a small app that relies heavily on this library and I'll surly participate with any features that comes to mind and  could add more value and convenience to the library.

**Comment by MohammadHH** [comment]
> @MohammadHH I don't have used typescript before. But I understood what it features. Can you please specify an example and usage for index.d.ts to the top of the License in README.md without modifying the existing content? If you do that, I think other people will be able to use this library more conveniently.

index.d.ts is a declaration file that will aid users when writing code.
If their RN app uses javascript it will aid them while coding in the IDE, and if
they use typescript they will also have a set of types that they can use.
I think I can add a section called typescript and put an example their.

**Pull request merged**
